revert pre-commit hook

diff --git a/tools/contrib/pre-commit b/tools/contrib/pre-commit
--- a/tools/contrib/pre-commit
+++ b/tools/contrib/pre-commit
@@ -26,4 +26,15 @@ do
 	fi
 done
 
+echo "Running Code Sniffer..."
+for FILE in $SFILES
+do
+	php bin/php-cs-fixer fix $PROJECT_PATH/$FILE --diff --level=psr2
+	if [ $? != 0 ]
+	then
+		echo "PSR2 errors found, please fix it before commit."
+		exit 1
+	fi
+done
+
 exit $?
